### ISSUE TITLE
List all missing controls on XML deserialisation

### ISSUE THREAD

**Issue by methusalah** [methusalah/OpenRTS#19]
Each time we type a wrong value in the XML and the engine bug instead of say what's wrong, we have to report it to create a control if possible.

**Comment by wuendsch** [comment]
Hi,
it's possible to translate? :bowtie:

**Comment by methusalah** [comment]
done !

**Comment by wuendsch** [comment]
hi, can you explain it in more detail? I dont understand what is to do here. What do you mean with control?

**Comment by methusalah** [comment]
When a user write an XML definition, he may make a lot of "mistakes", for exemple : 
 - Text case problem
 - a value out of range
 - a value unknown by the enigne
 - etc.
From typing errors or else. The code that read the definitions and create the bluprints (Builders) has  too few checks and may let errors pass throught.

For exemple, if you type an unknown element name, the code won't use its value and the defaut value will be used instead, leading to hard-to-source bugs.

We should found a way to solve that problem. The code must detect errors and throw warnings, or maybe there is another solution?

**Comment by wuendsch** [comment]
I prepare a EntityEditor (see here https://github.com/wuendsch/OpenRTS-EntityEditor). 
One of the last steps are now, to integrate it into our current system

**Comment by wuendsch** [comment]
The EntityEnditor is now released for a first beta version. It's possible that we integrate it directly into OpenRTS repository. I close this issue now.
