### ISSUE TITLE
Tiles can be stored as a wide String

### ISSUE THREAD

**Issue by methusalah** [methusalah/OpenRTS#50]
save and load would become fasert, and file smaller

**Comment by wuendsch** [comment]
What do you mean exactly with "wide string"? Do you have any example?

**Comment by methusalah** [comment]
I'm late here.

I asked Simple framework to serialize the tiles in XML format. The result is a huge file containing abolutly unnecessary data. This is awful and must be refactored.
First, it's useless to store the coordinates of tile as we save all tiles, ordered. Coordinates are implicits.
Second, there are more caracters for markup than for used data.

A solution would be to create our own serializer/deserializer for the Map class (with bytes or strings), as I did for the Atlas Class for the same reasons.

I'm sure you know a super-clean way to do that :)

**Comment by wuendsch** [comment]
I have problems to understand how the current serialisation is working. I understand we are using SimpleXML, the BuilderLibrary holding the Builders, but I can't understand, why is it so complex structured. It sounds a little bit naive, but the only thing we need is the create a instance for a object defined in XML(or other format) and while the runtime (if a new unit is spawned in the battlefield). 
Did I forgot any requirements?
Another question: should the fileformat being humanreadable(XML/JSON)?
or binary? see 
http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:save_and_load
http://wiki.jmonkeyengine.org/doku.php/jme3:contributions:cubes:tools:serialization

**Comment by methusalah** [comment]
This issue only concerns the map serialisation. There is no Builder involved here.

For the records, Builders are working with homemade XML parsing (in model.builders.definitions package). The user write the XML manually and the engine parse this XML into builders, which instanciate objetcs of this type.

The battlefield is serialized and deserialized by SimpleXML and hasn't to be humanreadable. For a battlefield, there is two files : one XML for the map and all components, and one binary for the ground texture atlas.

The XML contains : 
 - the map tiles,
 - the ramps,
 - the trinkets,
 - the engagement (units and buildings).

The problem are the tiles. They occupy 95% of the XML size. Each tile record contains : 
 - tile's coord
 - level
 - relief
 - cliffStyle as a String

The coord is useless (implicit by the order) ! And the cliffShape may be stored as an index, instead of a String.

Optimise this should reduce the weight of the XML (~3 or 4 now) and the loading time (very looong :)).

**Comment by wuendsch** [comment]
Thanks. now there is better understanding. 
Is it correct, that the user are writing some blueprints/templates... to describe the units/entities? If yes, this must be as easy as possible and naturally humanreadable. 

in the tiles aspect I am 100% with you. 
if we split the both things. In the map/battlefield there must only a reference for the unit. For example "a command like that "please insert an unit with id "humanId" at position X,Y (and some parameters like faction) (see https://github.com/methusalah/OpenRTS/issues/29)

**Comment by methusalah** [comment]
Yes, data directory hold XML written bu user. I tried to make it as easy as possible to write. I have to implement #29 to make it more efficient and less verbose.

battlefield may be entirely binary as the user won't have to read it. And yes, units are called by there definition ID only. hee is an example of the SimpleXML output : 

   <engagement>
      <initialEngagement class="java.util.ArrayList">
         <serializableUnit>
            <builderID>humantank</builderID>
            <factionName>1</factionName>
            <pos>
               <x>10.081957817077637</x>
               <y>4.811057806015015</y>
               <z>-0.6632389533061867</z>
            </pos>
            <yaw>0.48741929772002046</yaw>
         </serializableUnit>
      </initialEngagement>
   </engagement>

There are a lot of charaters for so few usefull data, but this is even worst with the tiles. Don't hesitate to open a .bf file in assets.maps to see more.

**Comment by wuendsch** [comment]
OK.and in last please look athttps://github.com/methusalah/OpenRTS/issues/19 and answer it. Than I have the bundle complete and I would fix iz ;-)

**Comment by methusalah** [comment]
Serialization/deserialization is much fatser with Jackson. I close for now.

**Comment by wuendsch** [comment]
map02 is not migrate to json. I will do it today. Till now I will reopen it. 
Another question is, Should we migrate the entities (units,weapons and so on) to JSON too?

**Comment by methusalah** [comment]
Entities could be in json as well, but it's much less urgent scince there is no performance issue.

**Comment by wuendsch** [comment]
The entityeditor (I am working on it now) will generate the new XMLs. The new one will be identical with the current one. Later we can change the generator to generate JSON. This will be easy.

**Comment by wuendsch** [comment]
but your are right, we can close this issue now. I report the status at https://github.com/methusalah/OpenRTS/issues/19
