### ISSUE TITLE
Eclipse project GeometryEclipseProject not found

### ISSUE THREAD

**Issue by wuendsch** [methusalah/OpenRTS#53]
hi,
after cloning and importing into eclipse, my eclipse doesn't find the project "GeometryEclipseProject" which is a decency of OpenRTs (see .classpath).
Where I can found it?

**Comment by wuendsch** [comment]
same in netbeans(JmonkeyPlattform): 
Problem: The project classpath includes a reference to the project called "Geometry", but this project was not found.
Solution: Click Resolve and locate the missing project.

**Comment by methusalah** [comment]
Hi and thanks for your issue. I'm currently setting up the repository and work is not yet finished. Please come back in a couple of days and it should be done.

**Comment by wuendsch** [comment]
hi,
thx for the info.If I can support you, please let me know.

**Comment by methusalah** [comment]
Thanks.

I'm only finishing to write a short description for most classes, include my geometry lib inside the repo and clean up the project. It shouldn't be long.

**Comment by wuendsch** [comment]
works now. thx.
