### ISSUE TITLE
support for JME Application States

### ISSUE THREAD

**Issue by wuendsch** [methusalah/OpenRTS#55]
Hi,

why you don't use JME's Application States? (see here
http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:application_states )
It's looking that you implement the same thing in your class controller.Controller.  Things like enabled/running/paused/updateLoop are implemented manually by you. Is there a reason for that?

Is it because you use a timer-speed-combination? And than you must handle you own Updateloop?
thanks for answering

**Comment by methusalah** [comment]
It has been done naturally and i've never loot at JME App States deeply. First I needed a controlleur to catch inputs, then The controller gained the model refresh responsibility, plus the GUI redraw, then I implemented a second controller and created a super class, etc etc.

If my implementation is close to JME App State, it is not intended, and I don't think to have specific needs so App States should certainly make the job.

Do you think it could be interesting to refactor?

**Comment by wuendsch** [comment]
absolutely. If there is an software pattern in JME like AppStates and its working good, then you should use it. So it's easier to understand for developers. And like you see in your implementation, this pattern is good, because you use it in the identical way. A refactoring should be easy. I will try it if it's ok.

**Comment by wuendsch** [comment]
done now with last commit.
