### ISSUE TITLE
Guide to project setup for asset contributors 

### ISSUE THREAD

**Issue by poVoq** [methusalah/OpenRTS#56]
Would be nice to expand the wiki a bit to explain in simple terms how to set up the jMonkeySDK for assets contributions.

If I get some pointers to try it myself, I can do the write-up in the wiki.

**Comment by methusalah** [comment]
I've updated the wiki to explain the jMonkey SDK walkthrought to setup the project.

https://github.com/methusalah/OpenRTS/wiki/Set-up-the-project-with-your-favorite-IDE-(Eclipse,-Netbeans,-etc.)

Please try and close that issue if it's OK. Don't hesitate to make a feedback if you have difficulties

**Comment by poVoq** [comment]
Had to set all the bins in /home/myName/jmonkeyplatform/jdk/jre/bin to excecutable on my fresh jMonkeyengine SDK install on Linux, then it worked. Maybe add a note that this might be necessary until that is fixed in the SDK.

**Comment by methusalah** [comment]
I added a note : https://github.com/methusalah/OpenRTS/wiki/Set-up-the-project-with-your-favorite-IDE-(Eclipse,-Netbeans,-etc.)#netbeans--jmonkey-sdk

Thanks
