### ISSUE TITLE
Error running after cloning in jMonkey Engine

### ISSUE THREAD

**Issue by poVoq** [methusalah/OpenRTS#58]
See error here:
https://gist.github.com/poVoq/146eef1878ffdad3dc9a
(I have no idea what I am looking at there), but it seems related to gradel see the debug output:
-----
Executing: gradle debug

Configuration on demand is an incubating feature.
/home/krischan/Projects/OpenRTS/core/src/model/battlefield/lighting/DirectionalLighting.java:7: error: package javafx.geometry does not exist
import javafx.geometry.Point3D;
                      ^
/home/krischan/Projects/OpenRTS/core/src/model/battlefield/lighting/DirectionalLighting.java:13: error: cannot find symbol
    public Point3D direction;
           ^
  symbol:   class Point3D
  location: class DirectionalLighting
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.259 secs
----

**Comment by methusalah** [comment]
I understand the issue, and I will fix it in a while

**Comment by methusalah** [comment]
should be good. pleas check and close if it's ok

**Comment by wuendsch** [comment]
acknowledged. working now. @poVoq closable now?

**Comment by poVoq** [comment]
Sorry not fixed yet it seems. It synced 2 files, but the model.battlefield.lightning->directionallightning.java is still shown as with an error ("error parsing file").
If I run a debug or just run try to run the game, the above error is still shown.

Probably unrelated, but I run it on an intel card with mesa drivers that supports only OpenGL 3.0. Still have to figure out how to get jMonkeySDK to use my Nvidia optimus card.

**Comment by wuendsch** [comment]
Hi,

are you sure, that you are on the last version? Did you pull the last version? Now the line 7 in DirectionalLighting.java is empty. The errormessage can't be the same.

**Comment by poVoq** [comment]
Ok, yeah I didn't know what I was doing. Thanks seems to work now ;)
