### ISSUE TITLE
Artstyle and back-ground story of the sample game

### ISSUE THREAD

**Issue by poVoq** [methusalah/OpenRTS#63]
Even though the main purpose of OpenRTS seems to be a general RTS engine, good software development practice suggests that this is developed while implementing a practical example.
I like the current idea to have a simple and very stylized art-style... a bit like what the game "Planetary Annihilation" is also doing. At the very least it allows rapid art creation, especially when the units are mainly non-humanoid and thus only require simple animations like a turret or some particle effects.

For the overall style and background I was thinking about expanding the existing art set towards a post-apocalyptic snowball-earth scenario that should go well with the more or less untextured low-poly art. 
The first faction would be then rather low tech tanks "diesel-punk" that the surviving population uses. The other faction could be aliens that invade the "empty" planet and try to terraform pockets on earth (with strange plants and fungi etc.). A third faction could be returning "high-tech" terrans that left shortly before the catastrophe to live in generation ships, but have now returned to "safe" the home-world from the alien invasion (and are not really welcome be the local humans either).

Focus would be competitive multiplayer and maybe SP/coop scenarios to play against an AI.

As you can see it is a bit of a Starcraft like scenario, that requires a snowy base level style, an alien terraform plant style, and maybe an orbital platform style for creating the various levels.

I am willing to work on the 3D art assets, but I will probably need some help as I don't have that much time. Therefore keeping the art requirements low is key to success I think.

**Comment by wuendsch** [comment]
Hi, I am on board.

**Comment by wuendsch** [comment]
First step I see: We need a empty game template with an OpenRTS dependency. I would create outside OpenRTS. I can create a repository for it. But I need a project name. Do you have a (working-)name for it?

**Comment by methusalah** [comment]
Maybe it's a little early for dependency? , the engine is immature and the
sample game very far from needing it.

The sample game won't interfere with the engine dev before a long time. I
think we may implement the game inside the actual repository, this allow
new users to fork the engine and watch at its possibilities at once. What
do you think?

About the scenario it's all good for me except for the general snowy style
which risks to lead to too few environnements. But with jungle domes,
orbital stations, ancient cities in ruins and caves, you can avoid that.

Please note that units have to contain inside and populate a sphere if
possible, to occupy the same place at any rotation angle. I will add this
note in the wiki.

Exciting!

Le dim. 10 mai 2015 15:54, Mario Meltzow <notifications@github.com> a
écrit :

**Comment by wuendsch** [comment]
I renamed the subproject desktop to example in the last commit. There we can start.

**Comment by poVoq** [comment]
Great! I will try to make a few prototype units meshes then. I am planning to make them pretty close in overall style to those in Starcraft2, i.e. pretty compact so that rotation wise we should be ok (better than the current tank that seems a bit too long).

**Comment by roroah** [comment]
I'll like to join too, but i got some few point to note : 
- There some missing information that i've didn't founded  (maybe i'm blind, or i did saw it but didn't noticed it) concerning the Assets licence !? what is the used licence for assets ?
I personnaly use the CC BY-SA 4.0 licence, but is there a general licence defined or is it up to each "artist" to choose is own licence ? (i'm not personnaly "ok" to have each assets his own licence since this lead to an huge mess but meh...)
- Then about the 3D prototype, isn't be better to have an "Art design document" See before going further as it would make stuff a lot easier and consistent. (it work if planning for the long run)

**Comment by methusalah** [comment]
For now by default, all assets included to the repository will definitly
fall under the same licence than the project itself : MIT
http://opensource.org/licenses/MIT. Content is public and free to use in
any project, commercial or not, with proper attribution (copyright) and
without warranty (no responsibilities). So you should put your ID into
every assets and that's all.

An asset may come with its own licence, like CC, or apache to add some
restrictions.

About a Art Design Document it's a very good idea and I'm sure you will
make something very useful after a little hacking and testing ^^ Seriously,
the original artist isn't available at this time and as you mentionned, the
project needs ressources to help futur artists to contribute easly. So feel
free to open an issue and propose your vision and your work on this point.

**Comment by wuendsch** [comment]
example game now has two main classes, one for starting the game, another for an editor. Any idea what can be the next step for implementation?

**Comment by methusalah** [comment]
The two mains must have their own saved display settings.

The game class should accept a map to run as parameter, to be launched by the editor directly.

And maybe it's time to add menus (app states) to the main game?

**Comment by wuendsch** [comment]
I look into and I see Benoit has removed the different settings methods, but I don't know why. Who is Benoit? Some of you guys? How we can handle the different settings now?

**Comment by methusalah** [comment]
Benoît is me ☺the default settings code wasn't used so I erased it, sorry.
But changes wasn't savable for each main. We have to separate settings for
each main completely, I'm not sure what is the best design.

**Comment by wuendsch** [comment]
Nifty is not my friend. May anyone prepare some views for it?

**Comment by methusalah** [comment]
I think I am the only nifty guy down here ☺ what do you need exactly?

Le dim. 17 mai 2015 13:54, Mario Meltzow <notifications@github.com> a
écrit :

**Comment by BRGCodeCampus** [comment]
What's Nifty used for ?

**Comment by methusalah** [comment]
Nifty gui is a framework for 2d gui

**Comment by BRGCodeCampus** [comment]
GUI can easily be made with VAO/VBOs and a very small Shader program

**Comment by methusalah** [comment]
Can't wait to see that in action 😁

**Comment by wuendsch** [comment]
perhaps some screens with button for "new game", "load map", "Connect to server" and something like that. Keep it simple ;-)

**Comment by wuendsch** [comment]
@BRGCodeCampus what is VAO/VBOs? And how we connect it with the java-classes to interact with some buttons an so on?

**Comment by BRGCodeCampus** [comment]
VAO (Vertex Array Object) stores VBO (Vertex Buffer Object) and is used to draw with modern OpenGL. To make buttons, we need to know the mouse coords on screen and then if it's in a GUI, and the user click, we can call a method to make what we want.

**Comment by roroah** [comment]
@BRGCodeCampus good to know about VBO & VAO :)
But, why switching to another gui instead of keeping to nifty ?
 what's the benefit from using the VAO/VBOs !?

**Comment by BRGCodeCampus** [comment]
Nifty doesn't seem to be well appreciated by some of us ;) so we search a homemade way to implement GUIs in OpenRTS, VAOs/VBOs are a "modern" way to do it with OpenGL and it's the one I know the best

**Comment by methusalah** [comment]
The issue isn't that Nifty is not appreciated, but that nobody has much experience with it. Nifty is very well implemented inside jMonkey Engine and it is the best solution to insert a simple but efficient GUI in no time.

VAO/VBO is a low level openGL aspect. To create a GUI framework half as effective as NiftyGUI, it will take a bunch of time. Much more than learning Nifty basis. I don't say it is worthless, but it may not be absolutly necessary for the moment.

That said, @BRGCodeCampus David, if you feel like creating a homemade GUI framework for OpenRTS, you're welcome I we will add this contribution with great pleasure ! ^^

And we will be able to have 3D animated GUI and that could be glorious ;-)

**Comment by wuendsch** [comment]
yes, 3D elements in Nifty is big problem. For a fast step we should use nifty, but a 3D GUI sounds really cool. +1 for it

**Comment by methusalah** [comment]
It appear that we have leaved the initial subject. I propose you to continu the discussion about the art style and story of the sample game on the new forum : 

http://hub.jmonkeyengine.org/t/artstyle-and-back-ground-story-of-the-sample-game/32613/1

Thanks !
