### ISSUE TITLE
Lower default resolution

### ISSUE THREAD

**Issue by poVoq** [methusalah/OpenRTS#64]
I changed it for myself in the main file, but I think it would be nice if it was possible to try out the game on typical laptop screen resolutions like 1366x786 without having to dive into the code.

**Comment by methusalah** [comment]
This is already a part of another issue about local parameters.  I close this one.

**Comment by methusalah** [comment]
it's done. the base resolution is now 1024*768, there is a button to change it, and the choice is saved locally
