### ISSUE TITLE
Hauteur maximale dans la classe HeightTool

### ISSUE THREAD

**Issue by BRGCodeCampus** [methusalah/OpenRTS#65]
N'ayant vu aucune sécurité sur la hauteur maximale du terrain avec l'outil height, j'en ai rajouté une.
Ma méthode est de définir une constante nommée MAX_HEIGHT et de tester si la hauteur est supérieure a cette constante, si oui, alors elle y est égale. 
EDIT : personnellement, j'ai mis MAX_HEIGHT a 50

**Comment by methusalah** [comment]
Pas faux, il faudra faire de même pour le min_height ^^

Attention, le projet est cosmopolite et l'anglais est de mise !

**Comment by BRGCodeCampus** [comment]
Sure but MIN_HEIGHT implicitly is 0 because we can't make the heigth negative. So I'm not sure it would be useful to make it explicitly.

**Comment by methusalah** [comment]
Terrain height can definitly be under 0.

**Comment by BRGCodeCampus** [comment]
I've seen it just after posting and made the changes

**Comment by methusalah** [comment]
Great ☺you may create a pull request, or paste the code change here and
I'll do the commit.

Thanks for the contribution!

**Comment by BRGCodeCampus** [comment]
here is the code

    private static final int MAX_HEIGHT = 30, MIN_HEIGHT = -10;
    private void raise(List<Tile> tiles){
        for(Tile t : tiles) {
            t.elevation += amplitude*pencil.strength*pencil.getApplicationRatio(t.getCoord());
            
            if(t.elevation > MAX_HEIGHT)
            	t.elevation = MAX_HEIGHT;
        }
    }
    
    private void low(List<Tile> tiles){
    	for(Tile t : tiles) {
            t.elevation -= amplitude*pencil.strength*pencil.getApplicationRatio(t.getCoord());
            
            if(t.elevation < MIN_HEIGHT)
            	t.elevation = MIN_HEIGHT;
        }
    }
