### ISSUE TITLE
No Units an Map

### ISSUE THREAD

**Issue by wuendsch** [methusalah/OpenRTS#71]
I want to load a map directly with Game.java. The game only contains the Battlefieldcontrollers (but no Editorcontrollers). any ideas why?

thx

**Comment by methusalah** [comment]
For now I can't test because of the dependencies' problem. I checked the engagment is correctly registred inside the army manager at battlefield load. I can't tell right now.

**Comment by wuendsch** [comment]
in class View there is a initialisation of an EditorRenderer, it's not needed in GameOnly mode. Perhaps there is the problem... I will investigate it in more detail.

**Comment by methusalah** [comment]
the Game class was only missing a loop ^^ actors where never drawn.

fixed

**Comment by wuendsch** [comment]
damned. thx
