### ISSUE TITLE
Guide for dataset contribution

### ISSUE THREAD

**Issue by roroah** [methusalah/OpenRTS#74]
I'll add some reference on what i think is missing for the assets contribution page.

- Specifies if a parameter is optional or not.
- Specifies what a param is needed for ?

https://github.com/methusalah/OpenRTS/wiki/Guide-for-dataset-contribution#unit
-  <MoverLink value="GroundProne"/> -> GroundProne is a define value or arbritrary ?

https://github.com/methusalah/OpenRTS/wiki/Guide-for-dataset-contribution#actor
https://github.com/methusalah/OpenRTS/wiki/Guide-for-dataset-contribution#mover
- these should be done since they seam to be required by the unit and projectile

As example of another way to present information (be kind i don't fully understand what each value is) : 
# Unit
    <Unit id="tank">
        <UIName value="simple combat armored vehicle"/>
        <Race value="human"/>
        <Radius value="0.8"/>
        <Speed value="4"/>
        <Mass value="1"/>
        <MaxHealth value="120"/>
        <MoverLink value="GroundProne"/>
        <WeaponList WeaponLink="TankCanon" TurretLink="TankTurret"/>
        <WeaponList WeaponLink="TankMachinegun" TurretLink="TankMachinegun"/>
        <WeaponList WeaponLink="TankFrontLaser"/>
        <ActorLink value="Tank"/>
    </Unit>

Required value : 
- MoverLink (see # Mover)
- ActorLink (see # Actor)
- MaxHealth (Maximum amount of health the unit have)
- Radius (Collision size of the unit)
- Mass (Acceleration and inertia...) (as side note i don't understand the inertia think, deceleration ?)
- Speed (How many meter does the unit move by sec (m/s))

Optional value : 
- WeaponList (one or many) (see # Weapon)
- UIName (Description name to use)
- Race (...idn...)

About the WeaponList the current one is kinda tricky, i think that it should be renamed WeaponLink and work like all other value, this give us :
-  WeaponLink value="TankCanon"
-  WeaponLink value="TankMachinegun"
-  WeaponLink value="TankFrontLaser"

Then the turret value would be stored inside the Weapon himself as : 
# Weapon
    <Weapon id="TankCanon".>
        <UIName value="ubber powerful canon"/> (I don't think this is needed)
        <EffectLink value="StdDamage"/>
        <Range value="5"/>
        <ScanRange value="7"/>
        <Period value="1.2"/>
        <ActorLink value="TankCanonMainActor"/>
        <SourceBone value="BMuzzle01"/>
        <DirectionBone value="BMuzzleVec01"/>
        <TurretLink value="TankTurret"/>
     </Weapon>

Required value : 
- EffectLink (see # Effect)
- ActorLink (see # Actor)
- SourceBone (projectile source)
- DirectionBone (projectile direction)
- Range (How far the weapon can shoot)
- Period (Delay between two attack)
- ScanRange (how far the unit start moving to get in range)

Optional value : 
- TurretLink (Is this weapon a turret)
- UIName (Description name to use)

**Comment by methusalah** [comment]
"GroundProne" is the ID of the mover to use. I will change it to a more generic term in the wiki.

About the presentation, indeed, I need to add info and make myself clearer :) I'll try it.

In the current nomenclature, $Link is a parameter containing the ID of another definition, $List is a parameter that may be used many times. It may be not wise to store the turret inside the unit def, because : 
 - a weapon may be reused with or without a turret (or another type of turret). Imagine a gatling under a plane wing, and mounted on a jeep
 - a turret may be used for many different weapons. Imagine multiple version of the same tank, holding a DCA or a canon, or a missile launcher...

Note that UInames shouldn't be optionnal, as it is shown inside the GUI on the mouseover for exemple.

**Comment by roroah** [comment]
$Link is a parameter containing the ID of another definition, $List is a parameter that may be used many times.
- Add this to the wiki so we know.
- I go the point about turret, you can forget what i'd said earlyer, but talk about the turret, the current name is still confusing since when we talk about turret we first think about static turret.
- keep in mind that what i wrote is just an exemple idn what is optional or not :D

**Comment by methusalah** [comment]
I adopted you suggestion because it seemed wise to me, thanks ! I will add a short description for the element to avoid any confusion about the "turret" term.

I also added you to collaborators, so you can contribute to the wiki as you wish.

If these changes fit this issue, we may close here :)

**Comment by roroah** [comment]
You welcome.
Yes we've done there, 
if you don't mind I'll add an issue for each missing part of the wiki.
