### ISSUE TITLE
  Guide for dataset contribution - Unit

### ISSUE THREAD

**Issue by roroah** [methusalah/OpenRTS#82]
Require completion : 
https://github.com/methusalah/OpenRTS/wiki/Guide-for-dataset-contribution#unit

Value definition for "Race" is missing.
What does that change to type a Race value ?

**Comment by methusalah** [comment]
This value is needed to regroup all building and units of a single gameplay/technology tree. "Race" may not be the correct terme and some will find "empire", "country" or "faction" more relevent, depending on the game they implement. The value is a character string like "Babylonians", "Brotherhood of the Nod", "Zerg"...

It differs from "faction" that is a geopolitically data to set up alliances and conflicts, regardless with the "race".
