### ISSUE TITLE
Guide for dataset contribution - Turret "BoneName"

### ISSUE THREAD

**Issue by roroah** [methusalah/OpenRTS#83]
In https://github.com/methusalah/OpenRTS/wiki/Guide-for-dataset-contribution#turret, 
- BoneName : The bone to rotate on the Unit's Actor's model. (?)
This isn't enough precise, the defined bone is held by the unit holding the turret or inside the turret itself ?
By that i mean does the turret require Bone ?
If the turret does not require bone, the Defined bone there, is a bone of the unit holding the turret.
So if i want my unit to have turret i need it to have a bone dedicated to it.
This mean each turret does no need any bone/armature.

**Comment by methusalah** [comment]
If I remember correctly, the bone must be attached to the turrets verticies, so when the bone rotate, all the turret rotates, with it as a pivot. I hope this answer the question.

Don't hesitate to complete the wiki with a more "modeler" langage ^^

**Comment by roroah** [comment]
I've updated the wiki.
