### ISSUE TITLE
Gradle build is long

### ISSUE THREAD

**Issue by methusalah** [methusalah/OpenRTS#85]
You can read it in the console while updating gradle dependecies.

It make the first build very long. Is there any solution?

Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-core/3.0.10/jme3-core-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-effects/3.0.10/jme3-effects-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-networking/3.0.10/jme3-networking-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-blender/3.0.10/jme3-blender-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-jbullet/3.0.10/jme3-jbullet-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-lwjgl/3.0.10/jme3-lwjgl-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
Download http://updates.jmonkeyengine.org/maven/com/jme3/jme3-niftygui/3.0.10/jme3-niftygui-3.0.10-sources.jar
NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt))
KERBEROS authentication error: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)

**Comment by meltzow** [comment]
how you get this messages? in the console its

**Comment by meltzow** [comment]
is this issue fixed now?

**Comment by meltzow** [comment]
no more reproducible. So I close this issue now
