### ISSUE TITLE
correct Logging

### ISSUE THREAD

**Issue by meltzow** [methusalah/OpenRTS#86]
see here http://wiki.jmonkeyengine.org/doku.php/jme3:advanced:logging

normally all files/components gets his own logger. Because of this we can enable and disable specific parts/components for logging in more details. For example info - logging while loading the Map or GUI. 

change the logging without change the source code can be handled with "logging.properties". I am not sure, if the file is read automatically. if not we can read it in source code.

**Comment by wuendsch** [comment]
example code for reading the logging properties
```Properties preferences = new Properties();
try {
    FileInputStream configFile = new FileInputStream("/path/to/app.properties");
    preferences.load(configFile);
    LogManager.getLogManager().readConfiguration(configFile);
} catch (IOException ex)
{
    System.out.println("WARNING: Could not open configuration file");
    System.out.println("WARNING: Logging not configured (console output only)");
}```

**Comment by meltzow** [comment]
fixed now. The logUtil is removed.
